version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/phd_website"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/phd-website-analytics-server"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/ddns-runner"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/duck-dns-server-mock"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/system-backupper"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"

