spring:
  mongodb:
    uri: mongodb://test:test@localhost:27017/analytics-server-db?authSource=admin

web:
  limiting:
    redis_url: redis://localhost:6379
  cors:
    mapping: '/**'
    allowed_origins:
      - '*'
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
