name: Analytics Server Continuous Integration And Artifact Publishing
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths: 
      - '.github/workflows/analytics-server-ci.yaml'
      - 'phd-website-analytics-server/**'
  push:
    tags:
      - 'analytics-server/*'

permissions:
  checks: write

jobs:
  build:
    runs-on: [self-hosted, arm64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Print java version
        run: java -version

      - name: Run gradle build
        working-directory: 'phd-website-analytics-server/'
        run: ./gradlew build --stacktrace

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Login to Docker Hub
        if: ${{ startsWith(github.ref, 'refs/tags/analytics-server/') }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        if: ${{ startsWith(github.ref, 'refs/tags/analytics-server/') }}
        working-directory: 'phd-website-analytics-server/'
        run: ./gradlew jib

