name: DDNS-Runner Continuous Integration And Artifact Publishing
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths: 
      - '.github/workflows/ddns-runner-ci.yaml'
      - 'ddns-runner/**'
  push:
    tags:
      - 'ddns-runner/*'
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install OpenSSL dependencies
        run: sudo apt install -y pkg-config libssl-dev

      - name: Build app in debug
        working-directory: ddns-runner
        run: cargo build

      - name: Run tests
        working-directory: ddns-runner
        run: cargo test

  publish-to-dockerub:
    needs: build-and-test
    runs-on: self-hosted
    if: ${{ startsWith(github.ref, 'refs/tags/ddns-runner/') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine version
        id: determine_version
        working-directory: ddns-runner
        run: echo "DDNS_VERSION=$(./tools/current-version.sh)" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "ddns-runner/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ddns-runner:${{ env.DDNS_VERSION }}
