name: System Backupper Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths: 
      - '.github/workflows/system-backupper.yaml'
      - 'system-backupper/**'
  push:
    tags:
      - 'system-backupper/*'
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - working-directory: system-backupper
        run: cargo build

      - working-directory: system-backupper
        run: cargo test

  e2e-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      # This step uses an already existing python installation.
      # The setup-python action does not work on self-hosted runners with Debian (any version) as for now.
      - name: Set up Python venv and dependencies
        working-directory: system-backupper/testing/e2e
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build docker image
        working-directory: system-backupper/testing/e2e
        run: docker compose build

      - name: Setup testing environment
        working-directory: system-backupper/testing/e2e
        run: docker compose up -d --wait

      - name: Run e2e tests
        working-directory: system-backupper/testing/e2e
        run: |
          source venv/bin/activate
          pytest *.py

      - name: Tear down testing environment
        if: always()
        working-directory: system-backupper/testing/e2e
        run: docker compose down -v

  publish-to-dockerhub:
    needs: [ build, e2e-tests]
    runs-on: self-hosted
    if: ${{ startsWith(github.ref, 'refs/tags/system-backupper/') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine version
        id: determine_version
        working-directory: system-backupper
        run: echo "SYSTEM_BACKUPPER_VERSION=$(./tools/current-version.sh)" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "system-backupper/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/system-backupper:${{ env.SYSTEM_BACKUPPER_VERSION }}
