name: Website Deployment
on:
  push:
    tags:
      - 'phdwebsite/*'

jobs:
  build:
    uses: ./.github/workflows/website-ci.yaml
    secrets: inherit

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: web-build-artifact
          path: phd_website/build/web

      - name: Connect to VPN
        run: |
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S sh -c "echo ${{ secrets.VPN_PASSWORD }} | sudo -S openconnect --background -u ${{ secrets.VPN_USER }} --protocol=gp ${{ secrets.VPN_GATEWAY }}"

      - name: Replace all files on target machine
        working-directory: phd_website
        run: ./scripts/ci/release.sh ${{ secrets.USERNAME }} ${{ secrets.HOST }} ${{ secrets.PATH }}

      - name: Disconnect from VPN
        if: always()
        run: |
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S killall -s SIGINT openconnect
